from collections.abc import Sequence
from pathlib import Path
from typing import Any, Final, final
__version__: Final[str]

@final
class Attachment:
    def __eq__(self, /, other: Attachment) -> bool: ...
    def __ge__(self, /, other: Attachment) -> bool: ...
    def __gt__(self, /, other: Attachment) -> bool: ...
    def __le__(self, /, other: Attachment) -> bool: ...
    def __lt__(self, /, other: Attachment) -> bool: ...
    def __ne__(self, /, other: Attachment) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def backlinks(self, /) -> set[str]: ...
    def full_path(self, /) -> str: ...
    @property
    def path(self, /) -> Path: ...
    def read_bytes(self, /) -> bytes: ...
    @property
    def vault_path(self, /) -> Path: ...

@final
class Callout:
    @property
    def foldable(self, /) -> bool: ...
    @foldable.setter
    def foldable(self, /, value: bool) -> None: ...
    @property
    def kind(self, /) -> str: ...
    @kind.setter
    def kind(self, /, value: str) -> None: ...
    @property
    def title(self, /) -> str: ...
    @title.setter
    def title(self, /, value: str) -> None: ...
    def to_markdown(self, /) -> str: ...
    @property
    def tokens(self, /) -> list[Token]: ...
    @tokens.setter
    def tokens(self, /, value: Sequence[Token]) -> None: ...

@final
class ExternalLink:
    def __repr__(self, /) -> str: ...
    @property
    def options(self, /) -> str |None: ...
    @options.setter
    def options(self, /, value: str |None) -> None: ...
    @property
    def position(self, /) -> str |None: ...
    @position.setter
    def position(self, /, value: str |None) -> None: ...
    @property
    def render(self, /) -> bool: ...
    @render.setter
    def render(self, /, value: bool) -> None: ...
    @property
    def show_how(self, /) -> str: ...
    @show_how.setter
    def show_how(self, /, value: str) -> None: ...
    def to_markdown(self, /) -> str: ...
    @property
    def url(self, /) -> str: ...
    @url.setter
    def url(self, /, value: str) -> None: ...

@final
class Frontmatter:
    def __delitem__(self, /, key: str) -> None: ...
    def __len__(self, /) -> int: ...
    def __new__(cls, /) -> Frontmatter: ...
    def __repr__(self, /) -> str: ...
    def clear(self, /) -> None: ...
    def contains(self, /, key: str) -> bool: ...
    def copy(self, /) -> Frontmatter: ...
    def dict(self, /) -> dict: ...
    def get(self, /, key: str) -> Any |None: ...
    def is_empty(self, /) -> bool: ...
    def items(self, /) -> list: ...
    def keys(self, /) -> list: ...
    def len(self, /) -> int: ...
    def remove(self, /, key: str) -> None: ...
    def set(self, /, key: str, value: Any) -> None: ...
    def values(self, /) -> list: ...
    def yaml(self, /, indent: int = 2) -> str: ...

@final
class InternalLink:
    @property
    def dest(self, /) -> str: ...
    @dest.setter
    def dest(self, /, value: str) -> None: ...
    @property
    def options(self, /) -> str |None: ...
    @options.setter
    def options(self, /, value: str |None) -> None: ...
    @property
    def position(self, /) -> str |None: ...
    @position.setter
    def position(self, /, value: str |None) -> None: ...
    @property
    def render(self, /) -> bool: ...
    @render.setter
    def render(self, /, value: bool) -> None: ...
    @property
    def show_how(self, /) -> str |None: ...
    @show_how.setter
    def show_how(self, /, value: str |None) -> None: ...
    def to_markdown(self, /) -> str: ...

@final
class Note:
    def __eq__(self, /, other: Note) -> bool: ...
    def __ge__(self, /, other: Note) -> bool: ...
    def __gt__(self, /, other: Note) -> bool: ...
    def __le__(self, /, other: Note) -> bool: ...
    def __len__(self, /) -> int: ...
    def __lt__(self, /, other: Note) -> bool: ...
    def __ne__(self, /, other: Note) -> bool: ...
    def __new__(cls, /, path: str, vault_path: str = "") -> Note: ...
    def __repr__(self, /) -> str: ...
    def all_tokens(self, /) -> list[Token]: ...
    @property
    def backlinks(self, /) -> set[str]: ...
    def frontmatter(self, /) -> Frontmatter |None: ...
    def full_path(self, /) -> Path: ...
    def insert_after_token(self, /, token: Token, text: str, offset: int = 0) -> None: ...
    def insert_at(self, /, pos: int, text: str) -> None: ...
    def insert_before_token(self, /, token: Token, text: str, offset: int = 0) -> None: ...
    @property
    def length(self, /) -> int: ...
    @property
    def links(self, /) -> set[str]: ...
    @property
    def name(self, /) -> str: ...
    def normalized_name(self, /) -> str: ...
    @property
    def path(self, /) -> Path: ...
    def read(self, /) -> str: ...
    def read_bytes(self, /) -> bytes: ...
    def replace_between(self, /, start: int, end: int, text: str) -> None: ...
    def replace_span(self, /, span: Span, text: str) -> None: ...
    def set_frontmatter(self, /, frontmatter: Frontmatter) -> None: ...
    @property
    def tags(self, /) -> set[str]: ...
    def tokens(self, /) -> list[Token]: ...
    @property
    def vault_path(self, /) -> Path: ...

@final
class Span:
    def __new__(cls, /, start: int, end: int) -> Span: ...
    def __repr__(self, /) -> str: ...
    @property
    def end(self, /) -> int: ...
    @property
    def start(self, /) -> int: ...

class Token:
    def __repr__(self, /) -> str: ...
    def to_markdown(self, /) -> str: ...
    @final
    class Bold(Token):
        __match_args__: Final = ("span", "marker", "tokens")
        def __new__(cls, /, span: Span, marker: str |None, tokens: Sequence[Token]) -> Token.Bold: ...
        @property
        def marker(self, /) -> str |None: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def tokens(self, /) -> list[Token]: ...
    @final
    class Callout(Token):
        __match_args__: Final = ("span", "callout")
        def __new__(cls, /, span: Span, callout: Callout) -> Token.Callout: ...
        @property
        def callout(self, /) -> Callout: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class CheckList(Token):
        __match_args__: Final = ("span", "items")
        def __new__(cls, /, span: Span, items: Sequence[Any]) -> Token.CheckList: ...
        @property
        def items(self, /) -> list[Any]: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Code(Token):
        __match_args__: Final = ("span", "lang", "code")
        def __new__(cls, /, span: Span, lang: str |None, code: str) -> Token.Code: ...
        @property
        def code(self, /) -> str: ...
        @property
        def lang(self, /) -> str |None: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Comment(Token):
        __match_args__: Final = ("span", "comment")
        def __new__(cls, /, span: Span, comment: str) -> Token.Comment: ...
        @property
        def comment(self, /) -> str: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class DisplayMath(Token):
        __match_args__: Final = ("span", "latex")
        def __new__(cls, /, span: Span, latex: str) -> Token.DisplayMath: ...
        @property
        def latex(self, /) -> str: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Divider(Token):
        __match_args__: Final = ("span",)
        def __new__(cls, /, span: Span) -> Token.Divider: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Escaped(Token):
        __match_args__: Final = ("span", "character")
        def __new__(cls, /, span: Span, character: str) -> Token.Escaped: ...
        @property
        def character(self, /) -> str: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class ExternalLink(Token):
        __match_args__: Final = ("span", "link")
        def __new__(cls, /, span: Span, link: ExternalLink) -> Token.ExternalLink: ...
        @property
        def link(self, /) -> ExternalLink: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Frontmatter(Token):
        __match_args__: Final = ("span", "yaml")
        def __new__(cls, /, span: Span, yaml: str) -> Token.Frontmatter: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def yaml(self, /) -> str: ...
    @final
    class Header(Token):
        __match_args__: Final = ("span", "level", "heading")
        def __new__(cls, /, span: Span, level: int, heading: str) -> Token.Header: ...
        @property
        def heading(self, /) -> str: ...
        @property
        def level(self, /) -> int: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Highlight(Token):
        __match_args__: Final = ("span", "marker", "tokens")
        def __new__(cls, /, span: Span, marker: str |None, tokens: Sequence[Token]) -> Token.Highlight: ...
        @property
        def marker(self, /) -> str |None: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def tokens(self, /) -> list[Token]: ...
    @final
    class InlineCode(Token):
        __match_args__: Final = ("span", "code")
        def __new__(cls, /, span: Span, code: str) -> Token.InlineCode: ...
        @property
        def code(self, /) -> str: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class InlineMath(Token):
        __match_args__: Final = ("span", "latex")
        def __new__(cls, /, span: Span, latex: str) -> Token.InlineMath: ...
        @property
        def latex(self, /) -> str: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class InternalLink(Token):
        __match_args__: Final = ("span", "link")
        def __new__(cls, /, span: Span, link: InternalLink) -> Token.InternalLink: ...
        @property
        def link(self, /) -> InternalLink: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Italic(Token):
        __match_args__: Final = ("span", "marker", "tokens")
        def __new__(cls, /, span: Span, marker: str |None, tokens: Sequence[Token]) -> Token.Italic: ...
        @property
        def marker(self, /) -> str |None: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def tokens(self, /) -> list[Token]: ...
    @final
    class List(Token):
        __match_args__: Final = ("span", "items")
        def __new__(cls, /, span: Span, items: Sequence[Any]) -> Token.List: ...
        @property
        def items(self, /) -> list[Any]: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class NumericList(Token):
        __match_args__: Final = ("span", "items")
        def __new__(cls, /, span: Span, items: Sequence[Any]) -> Token.NumericList: ...
        @property
        def items(self, /) -> list[Any]: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Quote(Token):
        __match_args__: Final = ("span", "tokens", "author")
        def __new__(cls, /, span: Span, tokens: Sequence[Token], author: str |None) -> Token.Quote: ...
        @property
        def author(self, /) -> str |None: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def tokens(self, /) -> list[Token]: ...
    @final
    class Strikethrough(Token):
        __match_args__: Final = ("span", "marker", "tokens")
        def __new__(cls, /, span: Span, marker: str |None, tokens: Sequence[Token]) -> Token.Strikethrough: ...
        @property
        def marker(self, /) -> str |None: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def tokens(self, /) -> list[Token]: ...
    @final
    class Table(Token):
        __match_args__: Final = ("span", "table")
        def __new__(cls, /, span: Span, table: Any) -> Token.Table: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def table(self, /) -> Any: ...
    @final
    class Tag(Token):
        __match_args__: Final = ("span", "tag")
        def __new__(cls, /, span: Span, tag: str) -> Token.Tag: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def tag(self, /) -> str: ...
    @final
    class TemplaterCommand(Token):
        __match_args__: Final = ("span", "command")
        def __new__(cls, /, span: Span, command: str) -> Token.TemplaterCommand: ...
        @property
        def command(self, /) -> str: ...
        @property
        def span(self, /) -> Span: ...
    @final
    class Text(Token):
        __match_args__: Final = ("span", "text")
        def __new__(cls, /, span: Span, text: str) -> Token.Text: ...
        @property
        def span(self, /) -> Span: ...
        @property
        def text(self, /) -> str: ...

@final
class Vault:
    def __new__(cls, /, path: str, ignore: Sequence[str] = ..., ignore_file: str |None = None, create: bool = False) -> Vault: ...
    def add_note(self, /, vault_path: str, content: str, reindex: bool = False) -> str: ...
    def attachment(self, /, name: str) -> Attachment |None: ...
    def attachments(self, /) -> list[Attachment]: ...
    @property
    def dangling_links(self, /) -> dict[str, list[str]]: ...
    def get_attachment_by_name(self, /, name: str) -> Attachment |None: ...
    def get_attachment_by_path(self, /, path: str) -> Attachment |None: ...
    def get_note_by_name(self, /, name: str) -> Note |None: ...
    def get_note_by_path(self, /, path: str) -> Note |None: ...
    def get_notes_by_tag(self, /, tag: str) -> list[Note]: ...
    @property
    def ignored(self, /) -> set[Path]: ...
    def index(self, /) -> None: ...
    def note(self, /, name: str) -> Note |None: ...
    def notes(self, /) -> list[Note]: ...
    @property
    def path(self, /) -> Path: ...
    def rename(self, /, old_name: str, new_name: str) -> None: ...
    def rename_tag(self, /, old_tag: str, new_tag: str) -> None: ...
    def tags(self, /) -> list[str]: ...

class VaultItem:
    @final
    class Attachment(VaultItem):
        __match_args__: Final = ("attachment",)
        def __new__(cls, /, attachment: Attachment) -> VaultItem.Attachment: ...
        @property
        def attachment(self, /) -> Attachment: ...
    @final
    class Note(VaultItem):
        __match_args__: Final = ("note",)
        def __new__(cls, /, note: Note) -> VaultItem.Note: ...
        @property
        def note(self, /) -> Note: ...

def normalize(name: str) -> str: ...
def parse_yaml(source: str) -> list: ...
def py_to_markdown(obj: Any) -> str: ...
def text_to_tokens(text: str) -> list[Token]: ...
