#!/usr/bin/env bash

# Check that the code does not contain "dbg!' statements
if grep -rn --include="*.rs" "dbg!(" src/ ;
then
  echo "Debug statements found in the code. Please remove them before committing."
  exit 1
fi

# Check formatting
cargo fmt --all -- --check || {
  echo "Code formatting issues found. Please run 'cargo fmt' to fix them."
  exit 1
}

# Check for linting issues
cargo clippy --all-targets --all-features -- -D warnings || {
  echo "Linting issues found. Please fix them before committing."
  exit 1
}

# Check documentation
RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features || {
  echo "Documntation issues found. Please fix them before committing."
  exit 1
}
